# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client__Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientMainWindow(object):
    def setupUi(self, ClientMainWindow):
        ClientMainWindow.setObjectName("ClientMainWindow")
        ClientMainWindow.resize(498, 630)
        ClientMainWindow.setStyleSheet("background-color: rgb(199, 171, 255);")
        self.centralwidget = QtWidgets.QWidget(ClientMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(180, 490, 141, 71))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(60, 255, 39);\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(340, 490, 141, 71))
        self.Delete_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("#Delete_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Delete_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.Save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Save_btn.setGeometry(QtCore.QRect(20, 490, 141, 71))
        self.Save_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Save_btn.setFont(font)
        self.Save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save_btn.setStyleSheet("#Save_btn{\n"
"background-color: rgb(112, 162, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(17, 21, 255);\n"
"}\n"
"#Save_btn:hover:pressed{\n"
"background-color: rgb(190, 164, 255);\n"
"}")
        self.Save_btn.setObjectName("Save_btn")
        self.Client = QtWidgets.QLineEdit(self.centralwidget)
        self.Client.setGeometry(QtCore.QRect(30, 160, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Client.setFont(font)
        self.Client.setStyleSheet("\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px Solid rgb(48, 252, 255);\n"
"border-radius: 18px;\n"
" ")
        self.Client.setText("")
        self.Client.setPlaceholderText("")
        self.Client.setObjectName("Client")
        self.Product = QtWidgets.QLineEdit(self.centralwidget)
        self.Product.setGeometry(QtCore.QRect(30, 290, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Product.setFont(font)
        self.Product.setStyleSheet("\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px Solid rgb(48, 252, 255);\n"
"border-radius: 18px;\n"
" ")
        self.Product.setText("")
        self.Product.setPlaceholderText("")
        self.Product.setObjectName("Product")
        self.Quantity = QtWidgets.QLineEdit(self.centralwidget)
        self.Quantity.setGeometry(QtCore.QRect(250, 390, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Quantity.setFont(font)
        self.Quantity.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px Solid rgb(48, 252, 255);\n"
"border-radius: 18px;\n"
" ")
        self.Quantity.setText("")
        self.Quantity.setPlaceholderText("")
        self.Quantity.setObjectName("Quantity")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 400, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 10, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(228, 20, 255);")
        self.label_4.setObjectName("label_4")
        ClientMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClientMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 29))
        self.menubar.setObjectName("menubar")
        ClientMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClientMainWindow)
        self.statusbar.setObjectName("statusbar")
        ClientMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ClientMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientMainWindow)

    def retranslateUi(self, ClientMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientMainWindow.setWindowTitle(_translate("ClientMainWindow", "MainWindow"))
        self.Search_btn.setText(_translate("ClientMainWindow", "Search "))
        self.Delete_btn.setText(_translate("ClientMainWindow", "Delete "))
        self.Save_btn.setText(_translate("ClientMainWindow", "Save "))
        self.label.setText(_translate("ClientMainWindow", "  Quantity :"))
        self.label_2.setText(_translate("ClientMainWindow", "Product :"))
        self.label_3.setText(_translate("ClientMainWindow", "Client :"))
        self.label_4.setText(_translate("ClientMainWindow", "Gestion  Achat"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ClientMainWindow = QtWidgets.QMainWindow()
#     ui = Ui_ClientMainWindow()
#     ui.setupUi(ClientMainWindow)
#     ClientMainWindow.show()
#     sys.exit(app.exec_())
